const String FlutterMessageChannelName = 'EtNet_FlutterIntegration';
const String advertisementWidget_routeName = "advertisementWidget";
const String loginPageWidget_routeName = "loginPageWidget";
const String sc_areaChartWidget_routeName = "sc_areaChartWidget";
const String sc_volChartWidget_routeName = "sc_volChartWidget";
const String sc_candlesTickWidget_routeName = "sc_candlesTickWidget";
//const String canvasChartWidget_routeName = "canvasChartWidget"; // TODO: Did not implement right now
const String qp_NssCoreWidget_routeName = "qp_NssCoreWidget";
const String qp_CommunicationWidget_routeName = "qp_CommunicationWidget";
const String fullScreenChartWidget_routeName = "fullScreenChartWidget";